# Generated by Django 4.0.6 on 2022-07-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('Case_Color', models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White')], default='BLA', max_length=20)),
                ('Case_Material', models.CharField(choices=[('PLA', 'Plastic'), ('POLY', 'Polycarbonate'), ('ALU', 'Aluminum')], default='ALU', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=20)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.keyboard')),
            ],
        ),
    ]
