# Generated by Django 4.0.6 on 2022-07-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_keyboard_user_delete_plate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plate',
        ),
    ]
