# Generated by Django 4.0.6 on 2022-07-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_plate'),
    ]

    operations = [
    ]
