# Generated by Django 4.0.6 on 2022-07-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220725_0500'),
    ]

    operations = [
    ]
