# Generated by Django 4.0.6 on 2022-07-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220725_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='Case_Layout',
            field=models.CharField(choices=[('ANSI', 'ANSI'), ('ISO', 'Isometric'), ('ORTHO', 'Ortholinear')], default='ANSI', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Case_Size',
            field=models.CharField(choices=[('100', 'Full Size'), ('80', 'TKL'), ('75', '75%'), ('100', 'Full Size'), ('80', 'TKL'), ('75', '75%'), ('65', '65%'), ('60', '60%'), ('40', '45%')], default='100', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Keycap_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White')], default='BLA', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Keycap_Legend',
            field=models.CharField(choices=[('TRUE', 'Yes'), ('FALSE', 'No')], default='TRUE', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Keycap_Name',
            field=models.CharField(default='GMK', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Keycap_Shinethrough',
            field=models.CharField(choices=[('TRUE', 'Yes'), ('FALSE', 'No')], default='TRUE', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Plate_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White')], default='BLA', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Plate_Material',
            field=models.CharField(choices=[('ALU', 'Aluminum'), ('BRA', 'Brass'), ('ORTHO', 'Ortholinear')], default='ALU', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Plate_Name',
            field=models.CharField(default='Glorious', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Switch_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White')], default='BLA', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Switch_Name',
            field=models.CharField(default='Cherry MX', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Switch_RGB',
            field=models.CharField(choices=[('TRUE', 'Yes'), ('FALSE', 'No')], default='TRUE', max_length=20),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Switch_Style',
            field=models.CharField(choices=[('CLI', 'Clicky'), ('SIL', 'Silent'), ('LIN', 'Linear'), ('TAC', 'Tactile'), ('OPT', 'Optical')], default='LIN', max_length=20),
        ),
    ]
