# Generated by Django 4.0.6 on 2022-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_keyboard_case_layout_keyboard_case_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='Case_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White'), ('BLU', 'Blue'), ('GRN', 'Green'), ('YLW', 'Yellow'), ('PRP', 'Purple'), ('ORG', 'Orange')], default='BLA', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Case_Material',
            field=models.CharField(choices=[('PLA', 'Plastic'), ('POLY', 'Polycarbonate'), ('ALU', 'Aluminum'), ('ACR', 'Acrylic'), ('WOOD', 'Wood')], default='ALU', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Case_Size',
            field=models.CharField(choices=[('100', 'Full Size'), ('80', 'TKL'), ('75', '75%'), ('65', '65%'), ('60', '60%'), ('40', '40%')], default='100', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Keycap_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White'), ('BLU', 'Blue'), ('GRN', 'Green'), ('YLW', 'Yellow'), ('PRP', 'Purple'), ('ORG', 'Orange')], default='BLA', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Plate_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White'), ('BLU', 'Blue'), ('GRN', 'Green'), ('YLW', 'Yellow'), ('PRP', 'Purple'), ('ORG', 'Orange')], default='BLA', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Plate_Material',
            field=models.CharField(choices=[('ALU', 'Aluminum'), ('BRS', 'Brass'), ('STL', 'Steel'), ('CBF', 'Carbon Fiber')], default='ALU', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Switch_Color',
            field=models.CharField(choices=[('BLA', 'Black'), ('RED', 'Red'), ('WHI', 'White'), ('BLU', 'Blue'), ('GRN', 'Green'), ('YLW', 'Yellow'), ('PRP', 'Purple'), ('ORG', 'Orange')], default='BLA', max_length=20),
        ),
    ]
